language: ruby
version: 1.9.3
before_script:
  - "sh -e /etc/init.d/xvfb start"
script: PADRINO_ENV=travis bundle exec rake

deploy:
  provider: heroku
  api_key: 979d3c95-7606-4caf-90e3-0a9d4d5f6076
  app: quetzal2
  on:
    repo: lrrinaudo/quetzal
    branch: master
