language: ruby
version: 1.9.3
before_script:
  - "sh -e /etc/init.d/xvfb start"
script: PADRINO_ENV=travis bundle exec rake

deploy:
  provider: heroku
  api_key: 416434ad-2488-4829-b4a0-ca7d43d84915
  app: quetzal-prueba
  on:
    repo: ruthgarcia/quetzal
    branch: master
